### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dromer** [akunull/piloslib#1]
Hey there! Noticed your set of vanilla abstractions. nice!
(can almost run this in heavy/hvcc, but we're still missing some things like list and vline~)

Do you mind attaching a license to your project, so it's clear under what conditions people can reuse your work?

thnx!

**Comment by akunull** [comment]
MIT license added. Would love to see this be used with heavy, most list objects are just for saving and loading though no vline~ might be tricky

**Comment by dromer** [comment]
Awesome! Yeah will have to investigate to what extend that behavior can be "emulated" or actually added to heavy. No idea yet but it's always nice to have more Vanilla abstractions! :)
